// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using avengers.Models;

namespace avengers.Migrations
{
    [DbContext(typeof(AvengerContext))]
    [Migration("20190928020329_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("avengers.Models.Comic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<DateTime>("Last_sync")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Tit_com")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("avengers.Models.Creador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_com")
                        .HasColumnName("ID_com");

                    b.Property<string>("Nom_cre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Rol_cre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Id_com");

                    b.ToTable("Creadores");
                });

            modelBuilder.Entity("avengers.Models.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_com")
                        .HasColumnName("ID_com");

                    b.Property<string>("Nom_per")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Id_com");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("avengers.Models.Creador", b =>
                {
                    b.HasOne("avengers.Models.Comic", "Comic")
                        .WithMany("Creador")
                        .HasForeignKey("Id_com")
                        .HasConstraintName("FK_Comics_Creadores");
                });

            modelBuilder.Entity("avengers.Models.Personaje", b =>
                {
                    b.HasOne("avengers.Models.Comic", "Comic")
                        .WithMany("Personaje")
                        .HasForeignKey("Id_com")
                        .HasConstraintName("FK_Comics_Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
